// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ChatroomsController from "./chatrooms_controller"
application.register("chatrooms", ChatroomsController)

import DreamsController from "./dreams_controller"
application.register("dreams", DreamsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TomselectController from "./tomselect_controller"
application.register("tomselect", TomselectController)
