// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomsController from "./chatrooms_controller"
application.register("chatrooms", ChatroomsController)

import DreamsController from "./dreams_controller"
application.register("dreams", DreamsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import TomselectController from "./tomselect_controller"
application.register("tomselect", TomselectController)
