tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/portable-ruby"
tap "homebrew/services"
brew "gh"
brew "git"
brew "imagemagick"
brew "jq"
brew "localtunnel"
brew "openssl@3"
brew "postgresql@13"
brew "postgresql@14", restart_service: true
brew "postgresql@15"
brew "rbenv"
brew "sqlite"
brew "wget"
brew "heroku/brew/heroku", link: false
cask "visual-studio-code"
